config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get '/webfonts/:font_file', to: redirect('/assets/webfonts/%{font_file}')
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "/feed" => "accounts#index"
  get "/profile/:username" => "accounts#profile", as: :profile
  #get "post/like/:post_id" => "likes#save", as: :save_like
  post "follow/account" => "accounts#follow_account", as: :follow_account

  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  resources :accounts do
    post 'unfollow', on: :member
  end

  root to: "home#homepage"

  get 'search', to: 'accounts#search'
  get '/followers/:username', to: 'accounts#followers', as: 'followers'
  get '/following/:username', to: 'accounts#following', as: 'following'

  resources :posts do
    get 'feed', on: :collection
    member do
      delete :destroy
    end
  end
  

end

app/models/post.rb
class Post < ApplicationRecord
    default_scope { order created_at: :desc }
    belongs_to :account

    has_many :likes
    has_many :comments

    has_one_attached :image

    validates :image, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id if account_signed_in?

    if @post.save
      redirect_to feed_path, flash: { success: "Post was created"}
    else
      redirect_to new_post_path, flash: { danger: "Post was not created"}
      puts @post.errors.full_messages
    end
  end

  def show
    @comment = Comment.new
  end

  def edit
    if @post.account_id != current_account.id
      redirect_to feed_path, flash: { danger: "You do not have permission to edit this post" }
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, flash: { success: "Post was updated" }
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.account_id == current_account.id
      if @post.destroy
        redirect_to feed_path, flash: { success: "Deleted" }
      else
        redirect_to post_path(@post), flash: { danger: "Error" }
      end
    else
      redirect_to feed_path, flash: { danger: "Wrong post" }
    end
  end
  

  private

  def set_post
    @post = Post.find(params[:id]) if params[:id].present?
  end

  def post_params
    params.require(:post).permit(:description, :caption, :image)
  end
end
  

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<% post.comments.each do |comment| %>
    <div class="comment">
        <% if comment.account_id == current_account.id %>
            <%= button_to '<i class="fa-regular fa-trash-can"></i>'.html_safe, comment_path(comment), method: :delete, data: { confirm: "Вы уверены, что хотите удалить этот комментарий?" }, class:"float-right", style: "border: none;" %>
        <% end %>
        <strong><%= link_to comment.account.username, profile_path(post.account.username), class: "text-dark" %></strong>
        <%= comment.comment %>
        <p class="text-muted"><%= time_ago_in_words comment.created_at %> ago</p>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit post</h2>

<%= form_for @post, html: { multipart: true } do |f| %>
  <p>
    <%= f.label :image %> <br>
    <%= f.file_field :image %>
  </p>
  <div class="form-group">
    <%= f.label :description%>
    <%= f.text_area :description, class: "form-control", style:"width: 525.6px;"%>
  </div>

  <p>
    <%= f.submit "Update", class: "btn btn-success" %>
  </p>

    
  

  
<% end %>

app/views/posts/index.html.erb
idk

app/views/posts/like.js.erb
<% if @success == true %>
$(".like-<%= @post_id %>").addClass("active");
<% end %>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= form_for @post, html: { multipart: true } do |f| %>
  <p>
    <%= f.label :image %> <br>
    <%= f.file_field :image %>
  </p>
  <div class="form-group">
    <%= f.label :description%>
    <%= f.text_area :description, class: "form-control", style:"width: 525.6px;"%>
  </div>

  <p>
    <%= f.submit "Save", class: "btn btn-success" %>
  </p>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
        <div class="inst-post float-right", style="height:666px; width:666px;">
          <%= image_tag @post.image if @post.image.present? %>
        </div>
    </div>

  <div class="col-4">
        <div class="post-meta">
              <%= link_to profile_picture(@post.account, 'pp-post'), profile_path(@post.account.username) %>
              <%= link_to @post.account.username, profile_path(@post.account.username), class: "text-dark"%>
        </div>

        <div class="post-details">
              <div class="post-actions">
                <div class="like">
                <%like = current_account.likes.find_by(post: @post)%>
                <% if like.nil?%>
                    <%= button_to '<i class="fa-solid fa-heart fa-2x"></i>'.html_safe, likes_path,  params: {like: {post_id:@post.id }}, method: :post, class: 'post-like'%>
                    
                <%else%>
                    <%= button_to '<i class="fa-solid fa-heart fa-2x active post-like"></i>'.html_safe, like_path(like), method: :delete, class: 'post-like' %>
                <%end%>          
                </div>
                <i class="fa-solid fa-message fa-2x post-comment"></i>

                <% if @post.account_id == current_account.id%>
                  <div class="edit-post"><%= link_to '<i class="fa-regular fa-pen-to-square fa-2x"></i>'.html_safe, edit_post_path %></div>
                <%end%>

                <% if @post.account_id == current_account.id %>            
                  <%= button_to '<i class="fa-regular fa-trash-can fa-2x edit-post"></i>'.html_safe, post_path(@post), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" } %>
                <% end %>

              </div>
              <p><strong><%= @post.likes.count %> likes</strong></p>
              <div><strong><%= link_to @post.account.username, profile_path(@post.account.username), class: "text-dark" %></strong></div>
              
              <%= simple_format @post.description %>

              <div class="comments-feed">
                <%= render "posts/comments", post: @post %>
              </div>

              <div class="text-muted"><%= time_ago_in_words @post.created_at %> ago</div>

            <div class="comment-box">
              <%= form_for @comment do |f| %>
                <%= f.hidden_field :post_id, value: @post.id %>
                <%= f.hidden_field :return_to, value: "post" %>
                <div class="input-group">
                <%= f.text_field :comment, placeholder: "Add comment here...", class: "form-control post-comment" %>
                  <div class="input-group-append">  
                    <%= f.submit "Post", class: "btn btn-light float-right", style: "margin-left: 1px; border-radius: 0px;"%>
                  </div>
                </div>
              <% end %>
            </div>

    </div>
  </div>
</div>