config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get '/webfonts/:font_file', to: redirect('/assets/webfonts/%{font_file}')
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "/feed" => "accounts#index"
  get "/profile/:username" => "accounts#profile", as: :profile
  #get "post/like/:post_id" => "likes#save", as: :save_like
  post "follow/account" => "accounts#follow_account", as: :follow_account

  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  resources :accounts do
    post 'unfollow', on: :member
  end

  root to: "home#homepage"

  get 'search', to: 'accounts#search'
  get '/followers/:username', to: 'accounts#followers', as: 'followers'
  get '/following/:username', to: 'accounts#following', as: 'following'

  resources :posts do
    get 'feed', on: :collection
    member do
      delete :destroy
    end
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Instapp</title>
        
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="instapp\app\assets\stylesheets\styles.css" />
  
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

</head>

  <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container">
                <a class="navbar-brand" href="/feed"><i class="fa-solid fa-camera"></i> Instapp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="search-box">
                        <% if account_signed_in? %>
                          <%= form_with(url: search_path, method: :get, local: true) do |form| %>
                            <%= form.text_field :search, value: params[:search], class: "post-comment", style: "margin-left: 1px; border-radius: 10px; border: 1px solid #ced4da; padding: 0.375rem 0.75rem;" %>
                            <%= form.submit "Search", class: "btn btn-light float-right", style: "margin-left: 1px; border-radius: none;"%>
                          <% end %>
                          </li>
                          <li class="nav-item active">
                            <%= link_to "Feed", feed_path, class: "nav-link" %>
                          </li>
                          <li class="nav-item active">
                            <%= link_to "New post", new_post_path, class: "nav-link" %>
                          </li>
                          <li class="nav-item active">
                            <%= link_to "Profile", profile_path(current_account.username), class: "nav-link" %>
                          </li>
                          <li class="nav-item active">
                            <%= link_to "Sing out🚪", destroy_account_session_path, 'data-turbo-method': :delete, class: "nav-link text-danger" %>
                          </li>
                        <% else %>

                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
          <div class="mt-5">
            <%= yield %>
          </div>
        </div>
    </body>
</html>