config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get '/webfonts/:font_file', to: redirect('/assets/webfonts/%{font_file}')
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "/feed" => "accounts#index"
  get "/profile/:username" => "accounts#profile", as: :profile
  #get "post/like/:post_id" => "likes#save", as: :save_like
  post "follow/account" => "accounts#follow_account", as: :follow_account

  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  resources :accounts do
    post 'unfollow', on: :member
  end

  root to: "home#homepage"

  get 'search', to: 'accounts#search'
  get '/followers/:username', to: 'accounts#followers', as: 'followers'
  get '/following/:username', to: 'accounts#following', as: 'following'

  resources :posts do
    get 'feed', on: :collection
    member do
      delete :destroy
    end
  end
  

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :first_name, presence: true

  has_one_attached :image
  
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  def self.search(search)
    if search
      where("username LIKE ?", "%#{search}%")
    else
      all
    end
  end

  def followers
    follower_ids = Follower.where(following_id: self.id).pluck(:follower_id)
    Account.where(id: follower_ids)
  end

  def following
    following_ids = Follower.where(follower_id: self.id).pluck(:following_id)
    Account.where(id: following_ids)
  end

  def total_followers
    Follower.where(following_id: self.id).count
  end

  def total_following
    Follower.where(follower_id: self.id).count
  end

  def following?(other_account)
    Follower.exists?(follower_id: self.id, following_id: other_account.id)
  end
  
  before_destroy :remove_followers_and_comments

  private

  def remove_followers_and_comments
    Follower.where(follower_id: self.id).delete_all
    Follower.where(following_id: self.id).delete_all
    Comment.where(account_id: self.id).delete_all
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_account! 
    before_action :set_account, only: [:profile] 

    def index
        following_ids = current_account.following.map(&:id)
        following_ids << current_account.id
        @posts = Post.where(account_id: following_ids)
        @comment = Comment.new
    
        @follower_suggestions = Account.where.not(id: following_ids)
    end

    def search
        @accounts = Account.search(params[:search])
    end

    def profile
        @posts = @account.posts
    end

    def followers
        @account = Account.find_by_username(params[:username])
        @followers = @account.followers
    end

    def following
        @account = Account.find_by_username(params[:username])
        @following = @account.following
    end

    def follow_account
        follower_id = params[:follow_id]
        if Follower.create!(follower_id: current_account.id, following_id: follower_id)
           flash[:success] = "Now following user" 
        else
            flash[:danger] = "Something wrong"
        end

        redirect_to profile_path(Account.find(follower_id).username)
    end

    def unfollow
        follow = Follower.find_by(follower_id: current_account.id, following_id: params[:id])
        if follow
          follow.destroy
          flash[:success] = "You have unfollowed the user"
        else
          flash[:danger] = "Something went wrong"
        end
        redirect_to profile_path(Account.find(params[:id]).username)
    end      

    def set_account
        @account = Account.find_by_username(params[:username])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

    def profile_picture(account, css_class = "")
        image_path = account.image.attached? ? url_for(account.image) : "default1.png"
        image_tag(image_path, class: css_class)
    end    

    def can_edit_profile profile_id
        account_signed_in? && current_account.id == profile_id
    end
end

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |account| %>
    <div class="recommended-follower">
        <div class="row">
            <div class="col-sm-3 col-lg-2">
                <%= link_to profile_picture(account, 'pp-post'), profile_path(account.username) %>
            </div>
            <div class="col-sm-9 col-lg-10">
                <%= form_tag follow_account_path, method: :post, class:"float-right" do %>
                    <%= hidden_field_tag :follow_id, account.id %>
                    <%= submit_tag "Follow", class: "btn btn-light btn-sm" %>
                <% end %>

                <%= link_to account.username, profile_path(account.username), class: "text-dark"%>
                <p class="text-muted"><%= account.created_at > 2.days.ago ? "New to Instapp" : "Followed by #{account.total_followers} users" %></p>
            </div>
        </div>
    </div>
<% end %>

app/views/accounts/followers.html.erb
<h2>Followers</h2>
<ul>
  <% @followers.each do |follower| %>
    <div class="follows">
        <div class="row">
            <div class="col-sm-3 col-lg-2">
                <%= link_to profile_picture(follower, 'pp-post'), profile_path(follower.username) %>
                <strong><%= link_to follower.username, profile_path(follower.username), class: "text-dark"%></strong>
            </div>
        </div>
    </div>
  <% end %>
</ul>

app/views/accounts/following.html.erb
<h2>Following</h2>
<% @account.following.each do |following| %>
    <div class="follows">
        <div class="row">
            <div class="col-sm-3 col-lg-2">
                <%= link_to profile_picture(following, 'pp-post'), profile_path(following.username) %>
                <strong><%= link_to following.username, profile_path(following.username), class: "text-dark"%></strong>
            </div>
            <div class="col-sm-9 col-lg-10">
                <% if current_account.following?(following) %>
                    <%= form_tag unfollow_account_path(following), method: :post, class:"float-right" do %>
                        <%= hidden_field_tag :follow_id, following.id %>
                        <%= submit_tag "Unfollow", class: "btn btn-danger btn-sm" %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

app/views/accounts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
        <% @posts.each do |post| %>
          <div class="inst-post">
            <div class="post-meta">
              <div class="pp-post"><%= link_to profile_picture(post.account, 'pp-post'), profile_path(post.account.username) %></div>
              <%= link_to post.account.username, profile_path(post.account.username), class: "text-dark"%>
            </div>

            <%= image_tag post.image %>

            <div class="post-details">
              <div class="post-actions">
                <div class="like">
                <%like = current_account.likes.find_by(post: post)%>
                <% if like.nil?%>
                    <%= button_to '<i class="fa-solid fa-heart fa-2x"></i>'.html_safe, likes_path,  params: {like: {post_id:post.id }}, method: :post, class: 'post-like'%>
                    
                <%else%>
                    <%= button_to '<i class="fa-solid fa-heart fa-2x active post-like"></i>'.html_safe, like_path(like), method: :delete, class: 'post-like' %>
                <%end%>          
                </div>
                <%= link_to post_path(post.id) do %>
                  <i class="fa-solid fa-message fa-2x post-comment"></i>
                <% end %>
              </div>
              
              <p><strong><%= post.likes.count %> likes</strong></p>
              <div><strong><%= link_to post.account.username, profile_path(post.account.username), class: "text-dark" %></strong></div>
              
              <%= simple_format post.description %>

              <%= render "posts/comments", post: post %>

              <div class="text-muted"><%= time_ago_in_words post.created_at %> ago</div>

            <div class="comment-box">
              <%= form_for @comment do |f| %>
                <%= f.hidden_field :post_id, value: post.id %>
                <div class="input-group">
                <%= f.text_field :comment, placeholder: "Add comment here...", class: "form-control post-comment" %>
                  <div class="input-group-append">  
                    <%= f.submit "Post", class: "btn btn-light float-right", style: "margin-left: 1px; border-radius: 0px;"%>
                  </div>
                </div>
              <% end %>
            </div>
            </div>
          </div>
        <% end %>
    </div>
    <div class="col-4">
      <div class="account-summary" style="display: flex; align-items: top;">
        <p style="margin-right: 10px;">
          <%= link_to profile_picture(current_account, 'pp-summ'), profile_path(current_account.username) %>
        </p>
        <div>
          <strong><%= link_to current_account.username, profile_path(current_account.username), class: "text-dark"%></strong><br />
          <%= current_account.first_name %> <%= current_account.last_name %>
        </div>
      </div>
      
      <div class="follower-suggestions">
        <p class="text-muted">Suggestions for you</p>
        <%= render "accounts/follower_suggestions" %>
      </div>
    </div>
  </div>
</div>

app/views/accounts/like.js.erb
document.addEventListener("DOMContentLoaded", function() {
    const postLikeButtons = document.querySelectorAll(".post-like");
    
    postLikeButtons.forEach(button => {
        button.addEventListener("click", function() {
            const post_id = button.getAttribute("data-id");
            
            fetch(`/post/like/${post_id}`)
                .then(response => response.text())
                .then(data => {
                    console.log(data);
                })
                .catch(error => {
                    console.error("Error fetching data:", error);
                });
        });
    });
});

app/views/accounts/profile.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
             <%= profile_picture @account, "profile-pic" %>
        </div>
        <div class="col-8 text-left">
            <h1><%= @account.username %></h1>
            <h6 class="text-muted", style="font-weight: normal;"><%= @account.first_name %> <%= @account.last_name %></h6>
            
            <div class="profile-stats"><%= @account.posts.count %> posts</div>

            <div class="profile-stats">
                <%= link_to "#{@account.total_followers} followers", followers_path(@account.username), class: "text-dark" %>
            </div>

            <div class="profile-stats">
                <%= link_to "#{@account.total_following} following", following_path(@account.username), class: "text-dark" %>
            </div>

            <% if can_edit_profile(@account.id) %>
                <%= link_to '<i class="fa-solid fa-pen"></i>'.html_safe, edit_account_registration_path, class: "btn btn-secondary" %>
            <% elsif current_account.following?(@account) %>
                <%= form_tag unfollow_account_path(@account), method: :post do %>
                    <%= hidden_field_tag :follow_id, @account.id %>
                    <%= submit_tag "Unfollow", class: "btn btn-danger btn-sm" %>
            <% end %>
                <% else %>
                    <%= form_tag follow_account_path(@account), method: :post do %>
                        <%= hidden_field_tag :follow_id, @account.id %>
                        <%= submit_tag "Follow", class: "btn btn-info btn-sm" %>
                <% end %>
            <% end %>

            <p><%= simple_format @account.description %></p>
            <% if @account.website.present? %>
                <p><a href="<%= @account.website %>"><%= @account.website %></a></p>
            <% end %>
        </div>
    </div>

    <div class="row profile-posts">
            <% @posts.each do |post| %>
             <div class="col-4">
              <div class="profile-pics">
                    <%= link_to image_tag(post.image), post_path(post) %>
              </div>
             </div> 
            <% end %>
    </div>
</div>

app/views/accounts/search.html.erb
<h2>Searching results</h2>
<ul>
  <% @accounts.each do |account| %>
    <div class="follows">
        <div class="row">
            <div class="col-sm-3 col-lg-2">
                <%= link_to profile_picture(account, 'pp-post'), profile_path(account.username) %>
                <strong><%= link_to account.username, profile_path(account.username), class: "text-dark"%></strong>
            </div>

            <div class="col-sm-9 col-lg-10">
                <% unless current_account.following?(account) %>
                    <%= form_tag follow_account_path(account), method: :post do %>
                        <%= hidden_field_tag :follow_id, account.id %>
                        <%= submit_tag "Follow", class: "btn btn-info btn-sm" %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
  <% end %>
</ul>